# Generated by Django 3.0.2 on 2021-07-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pub_date',
        ),
    ]
